# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import grpc_test_pb2 as grpc__test__pb2


class ProtoTestStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.doRequest = channel.unary_unary(
                '/grpc_test.ProtoTest/doRequest',
                request_serializer=grpc__test__pb2.MessageData.SerializeToString,
                response_deserializer=grpc__test__pb2.MessageData.FromString,
                )


class ProtoTestServicer(object):
    """Missing associated documentation comment in .proto file."""

    def doRequest(self, request, context):
        """正常请求
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProtoTestServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'doRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.doRequest,
                    request_deserializer=grpc__test__pb2.MessageData.FromString,
                    response_serializer=grpc__test__pb2.MessageData.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpc_test.ProtoTest', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ProtoTest(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def doRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc_test.ProtoTest/doRequest',
            grpc__test__pb2.MessageData.SerializeToString,
            grpc__test__pb2.MessageData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
