# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_test.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fgrpc_test.proto\x12\tgrpc_test\")\n\x06Vector\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\"3\n\nVectorList\x12%\n\npoint_list\x18\x01 \x03(\x0b\x32\x11.grpc_test.Vector\":\n\x0cGetMinDisReq\x12*\n\x0bpoint_lists\x18\x01 \x03(\x0b\x32\x15.grpc_test.VectorList\"\x1f\n\x0cGetMinDisRsp\x12\x0f\n\x07min_dis\x18\x01 \x03(\x02\"\x16\n\x07NumList\x12\x0b\n\x03num\x18\x01 \x03(\x02\":\n\x12\x43ountAndSumListReq\x12$\n\x08num_list\x18\x01 \x03(\x0b\x32\x12.grpc_test.NumList\"\xa1\x01\n\x16\x43ountAndSumResInstruct\x12\x44\n\ncount_dict\x18\x01 \x03(\x0b\x32\x30.grpc_test.CountAndSumResInstruct.CountDictEntry\x12\x0f\n\x07sum_res\x18\x02 \x01(\x02\x1a\x30\n\x0e\x43ountDictEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\"R\n\x12\x43ountAndSumListRsp\x12<\n\x11\x63ount_and_sum_res\x18\x01 \x03(\x0b\x32!.grpc_test.CountAndSumResInstruct\"\x13\n\x06Letter\x12\t\n\x01s\x18\x01 \x01(\t\"9\n\x0fUpperLettersReq\x12&\n\x0bletter_list\x18\x01 \x03(\x0b\x32\x11.grpc_test.Letter\"=\n\x0fUpperLettersRsp\x12*\n\x0fletter_res_list\x18\x01 \x03(\x0b\x32\x11.grpc_test.Letter\"5\n\x0bMessageData\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\x32J\n\tProtoTest\x12=\n\tdoRequest\x12\x16.grpc_test.MessageData\x1a\x16.grpc_test.MessageData\"\x00\x62\x06proto3')



_VECTOR = DESCRIPTOR.message_types_by_name['Vector']
_VECTORLIST = DESCRIPTOR.message_types_by_name['VectorList']
_GETMINDISREQ = DESCRIPTOR.message_types_by_name['GetMinDisReq']
_GETMINDISRSP = DESCRIPTOR.message_types_by_name['GetMinDisRsp']
_NUMLIST = DESCRIPTOR.message_types_by_name['NumList']
_COUNTANDSUMLISTREQ = DESCRIPTOR.message_types_by_name['CountAndSumListReq']
_COUNTANDSUMRESINSTRUCT = DESCRIPTOR.message_types_by_name['CountAndSumResInstruct']
_COUNTANDSUMRESINSTRUCT_COUNTDICTENTRY = _COUNTANDSUMRESINSTRUCT.nested_types_by_name['CountDictEntry']
_COUNTANDSUMLISTRSP = DESCRIPTOR.message_types_by_name['CountAndSumListRsp']
_LETTER = DESCRIPTOR.message_types_by_name['Letter']
_UPPERLETTERSREQ = DESCRIPTOR.message_types_by_name['UpperLettersReq']
_UPPERLETTERSRSP = DESCRIPTOR.message_types_by_name['UpperLettersRsp']
_MESSAGEDATA = DESCRIPTOR.message_types_by_name['MessageData']
Vector = _reflection.GeneratedProtocolMessageType('Vector', (_message.Message,), {
  'DESCRIPTOR' : _VECTOR,
  '__module__' : 'grpc_test_pb2'
  # @@protoc_insertion_point(class_scope:grpc_test.Vector)
  })
_sym_db.RegisterMessage(Vector)

VectorList = _reflection.GeneratedProtocolMessageType('VectorList', (_message.Message,), {
  'DESCRIPTOR' : _VECTORLIST,
  '__module__' : 'grpc_test_pb2'
  # @@protoc_insertion_point(class_scope:grpc_test.VectorList)
  })
_sym_db.RegisterMessage(VectorList)

GetMinDisReq = _reflection.GeneratedProtocolMessageType('GetMinDisReq', (_message.Message,), {
  'DESCRIPTOR' : _GETMINDISREQ,
  '__module__' : 'grpc_test_pb2'
  # @@protoc_insertion_point(class_scope:grpc_test.GetMinDisReq)
  })
_sym_db.RegisterMessage(GetMinDisReq)

GetMinDisRsp = _reflection.GeneratedProtocolMessageType('GetMinDisRsp', (_message.Message,), {
  'DESCRIPTOR' : _GETMINDISRSP,
  '__module__' : 'grpc_test_pb2'
  # @@protoc_insertion_point(class_scope:grpc_test.GetMinDisRsp)
  })
_sym_db.RegisterMessage(GetMinDisRsp)

NumList = _reflection.GeneratedProtocolMessageType('NumList', (_message.Message,), {
  'DESCRIPTOR' : _NUMLIST,
  '__module__' : 'grpc_test_pb2'
  # @@protoc_insertion_point(class_scope:grpc_test.NumList)
  })
_sym_db.RegisterMessage(NumList)

CountAndSumListReq = _reflection.GeneratedProtocolMessageType('CountAndSumListReq', (_message.Message,), {
  'DESCRIPTOR' : _COUNTANDSUMLISTREQ,
  '__module__' : 'grpc_test_pb2'
  # @@protoc_insertion_point(class_scope:grpc_test.CountAndSumListReq)
  })
_sym_db.RegisterMessage(CountAndSumListReq)

CountAndSumResInstruct = _reflection.GeneratedProtocolMessageType('CountAndSumResInstruct', (_message.Message,), {

  'CountDictEntry' : _reflection.GeneratedProtocolMessageType('CountDictEntry', (_message.Message,), {
    'DESCRIPTOR' : _COUNTANDSUMRESINSTRUCT_COUNTDICTENTRY,
    '__module__' : 'grpc_test_pb2'
    # @@protoc_insertion_point(class_scope:grpc_test.CountAndSumResInstruct.CountDictEntry)
    })
  ,
  'DESCRIPTOR' : _COUNTANDSUMRESINSTRUCT,
  '__module__' : 'grpc_test_pb2'
  # @@protoc_insertion_point(class_scope:grpc_test.CountAndSumResInstruct)
  })
_sym_db.RegisterMessage(CountAndSumResInstruct)
_sym_db.RegisterMessage(CountAndSumResInstruct.CountDictEntry)

CountAndSumListRsp = _reflection.GeneratedProtocolMessageType('CountAndSumListRsp', (_message.Message,), {
  'DESCRIPTOR' : _COUNTANDSUMLISTRSP,
  '__module__' : 'grpc_test_pb2'
  # @@protoc_insertion_point(class_scope:grpc_test.CountAndSumListRsp)
  })
_sym_db.RegisterMessage(CountAndSumListRsp)

Letter = _reflection.GeneratedProtocolMessageType('Letter', (_message.Message,), {
  'DESCRIPTOR' : _LETTER,
  '__module__' : 'grpc_test_pb2'
  # @@protoc_insertion_point(class_scope:grpc_test.Letter)
  })
_sym_db.RegisterMessage(Letter)

UpperLettersReq = _reflection.GeneratedProtocolMessageType('UpperLettersReq', (_message.Message,), {
  'DESCRIPTOR' : _UPPERLETTERSREQ,
  '__module__' : 'grpc_test_pb2'
  # @@protoc_insertion_point(class_scope:grpc_test.UpperLettersReq)
  })
_sym_db.RegisterMessage(UpperLettersReq)

UpperLettersRsp = _reflection.GeneratedProtocolMessageType('UpperLettersRsp', (_message.Message,), {
  'DESCRIPTOR' : _UPPERLETTERSRSP,
  '__module__' : 'grpc_test_pb2'
  # @@protoc_insertion_point(class_scope:grpc_test.UpperLettersRsp)
  })
_sym_db.RegisterMessage(UpperLettersRsp)

MessageData = _reflection.GeneratedProtocolMessageType('MessageData', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGEDATA,
  '__module__' : 'grpc_test_pb2'
  # @@protoc_insertion_point(class_scope:grpc_test.MessageData)
  })
_sym_db.RegisterMessage(MessageData)

_PROTOTEST = DESCRIPTOR.services_by_name['ProtoTest']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _COUNTANDSUMRESINSTRUCT_COUNTDICTENTRY._options = None
  _COUNTANDSUMRESINSTRUCT_COUNTDICTENTRY._serialized_options = b'8\001'
  _VECTOR._serialized_start=30
  _VECTOR._serialized_end=71
  _VECTORLIST._serialized_start=73
  _VECTORLIST._serialized_end=124
  _GETMINDISREQ._serialized_start=126
  _GETMINDISREQ._serialized_end=184
  _GETMINDISRSP._serialized_start=186
  _GETMINDISRSP._serialized_end=217
  _NUMLIST._serialized_start=219
  _NUMLIST._serialized_end=241
  _COUNTANDSUMLISTREQ._serialized_start=243
  _COUNTANDSUMLISTREQ._serialized_end=301
  _COUNTANDSUMRESINSTRUCT._serialized_start=304
  _COUNTANDSUMRESINSTRUCT._serialized_end=465
  _COUNTANDSUMRESINSTRUCT_COUNTDICTENTRY._serialized_start=417
  _COUNTANDSUMRESINSTRUCT_COUNTDICTENTRY._serialized_end=465
  _COUNTANDSUMLISTRSP._serialized_start=467
  _COUNTANDSUMLISTRSP._serialized_end=549
  _LETTER._serialized_start=551
  _LETTER._serialized_end=570
  _UPPERLETTERSREQ._serialized_start=572
  _UPPERLETTERSREQ._serialized_end=629
  _UPPERLETTERSRSP._serialized_start=631
  _UPPERLETTERSRSP._serialized_end=692
  _MESSAGEDATA._serialized_start=694
  _MESSAGEDATA._serialized_end=747
  _PROTOTEST._serialized_start=749
  _PROTOTEST._serialized_end=823
# @@protoc_insertion_point(module_scope)
