# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import grpc_test_pb2 as grpc__test__pb2


class GetMimDisServiceStub(object):
    """定义服务
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMinDis = channel.unary_unary(
                '/grpc_test.GetMimDisService/GetMinDis',
                request_serializer=grpc__test__pb2.GetMinDisReq.SerializeToString,
                response_deserializer=grpc__test__pb2.GetMinDisRsp.FromString,
                )


class GetMimDisServiceServicer(object):
    """定义服务
    """

    def GetMinDis(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GetMimDisServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMinDis': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMinDis,
                    request_deserializer=grpc__test__pb2.GetMinDisReq.FromString,
                    response_serializer=grpc__test__pb2.GetMinDisRsp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpc_test.GetMimDisService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GetMimDisService(object):
    """定义服务
    """

    @staticmethod
    def GetMinDis(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc_test.GetMimDisService/GetMinDis',
            grpc__test__pb2.GetMinDisReq.SerializeToString,
            grpc__test__pb2.GetMinDisRsp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
