// 编译命令：protoc --go_out=. --go-grpc_out=. -I . grpc_test.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.26.0
// source: grpc_test.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProtoTest_DoRequest_FullMethodName = "/grpc_test.ProtoTest/doRequest"
)

// ProtoTestClient is the client API for ProtoTest service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProtoTestClient interface {
	// 正常请求
	DoRequest(ctx context.Context, in *MessageData, opts ...grpc.CallOption) (*MessageData, error)
}

type protoTestClient struct {
	cc grpc.ClientConnInterface
}

func NewProtoTestClient(cc grpc.ClientConnInterface) ProtoTestClient {
	return &protoTestClient{cc}
}

func (c *protoTestClient) DoRequest(ctx context.Context, in *MessageData, opts ...grpc.CallOption) (*MessageData, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MessageData)
	err := c.cc.Invoke(ctx, ProtoTest_DoRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProtoTestServer is the server API for ProtoTest service.
// All implementations must embed UnimplementedProtoTestServer
// for forward compatibility.
type ProtoTestServer interface {
	// 正常请求
	DoRequest(context.Context, *MessageData) (*MessageData, error)
	mustEmbedUnimplementedProtoTestServer()
}

// UnimplementedProtoTestServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProtoTestServer struct{}

func (UnimplementedProtoTestServer) DoRequest(context.Context, *MessageData) (*MessageData, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DoRequest not implemented")
}
func (UnimplementedProtoTestServer) mustEmbedUnimplementedProtoTestServer() {}
func (UnimplementedProtoTestServer) testEmbeddedByValue()                   {}

// UnsafeProtoTestServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProtoTestServer will
// result in compilation errors.
type UnsafeProtoTestServer interface {
	mustEmbedUnimplementedProtoTestServer()
}

func RegisterProtoTestServer(s grpc.ServiceRegistrar, srv ProtoTestServer) {
	// If the following call pancis, it indicates UnimplementedProtoTestServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProtoTest_ServiceDesc, srv)
}

func _ProtoTest_DoRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProtoTestServer).DoRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProtoTest_DoRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProtoTestServer).DoRequest(ctx, req.(*MessageData))
	}
	return interceptor(ctx, in, info, handler)
}

// ProtoTest_ServiceDesc is the grpc.ServiceDesc for ProtoTest service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProtoTest_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc_test.ProtoTest",
	HandlerType: (*ProtoTestServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "doRequest",
			Handler:    _ProtoTest_DoRequest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc_test.proto",
}
