// 编译命令：protoc --go_out=. --go-grpc_out=. -I . grpc_test.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.26.0
// source: grpc_test.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GetMimDisService_GetMinDis_FullMethodName = "/grpc_test.GetMimDisService/GetMinDis"
)

// GetMimDisServiceClient is the client API for GetMimDisService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 定义服务
type GetMimDisServiceClient interface {
	GetMinDis(ctx context.Context, in *GetMinDisReq, opts ...grpc.CallOption) (*GetMinDisRsp, error)
}

type getMimDisServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGetMimDisServiceClient(cc grpc.ClientConnInterface) GetMimDisServiceClient {
	return &getMimDisServiceClient{cc}
}

func (c *getMimDisServiceClient) GetMinDis(ctx context.Context, in *GetMinDisReq, opts ...grpc.CallOption) (*GetMinDisRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMinDisRsp)
	err := c.cc.Invoke(ctx, GetMimDisService_GetMinDis_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetMimDisServiceServer is the server API for GetMimDisService service.
// All implementations must embed UnimplementedGetMimDisServiceServer
// for forward compatibility.
//
// 定义服务
type GetMimDisServiceServer interface {
	GetMinDis(context.Context, *GetMinDisReq) (*GetMinDisRsp, error)
	mustEmbedUnimplementedGetMimDisServiceServer()
}

// UnimplementedGetMimDisServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGetMimDisServiceServer struct{}

func (UnimplementedGetMimDisServiceServer) GetMinDis(context.Context, *GetMinDisReq) (*GetMinDisRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMinDis not implemented")
}
func (UnimplementedGetMimDisServiceServer) mustEmbedUnimplementedGetMimDisServiceServer() {}
func (UnimplementedGetMimDisServiceServer) testEmbeddedByValue()                          {}

// UnsafeGetMimDisServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GetMimDisServiceServer will
// result in compilation errors.
type UnsafeGetMimDisServiceServer interface {
	mustEmbedUnimplementedGetMimDisServiceServer()
}

func RegisterGetMimDisServiceServer(s grpc.ServiceRegistrar, srv GetMimDisServiceServer) {
	// If the following call pancis, it indicates UnimplementedGetMimDisServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GetMimDisService_ServiceDesc, srv)
}

func _GetMimDisService_GetMinDis_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMinDisReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetMimDisServiceServer).GetMinDis(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GetMimDisService_GetMinDis_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetMimDisServiceServer).GetMinDis(ctx, req.(*GetMinDisReq))
	}
	return interceptor(ctx, in, info, handler)
}

// GetMimDisService_ServiceDesc is the grpc.ServiceDesc for GetMimDisService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GetMimDisService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc_test.GetMimDisService",
	HandlerType: (*GetMimDisServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMinDis",
			Handler:    _GetMimDisService_GetMinDis_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc_test.proto",
}
