# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_test.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fgrpc_test.proto\x12\tgrpc_test\")\n\x06Vector\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\"3\n\nVectorList\x12%\n\npoint_list\x18\x01 \x03(\x0b\x32\x11.grpc_test.Vector\":\n\x0cGetMinDisReq\x12*\n\x0bpoint_lists\x18\x01 \x03(\x0b\x32\x15.grpc_test.VectorList\"\x1f\n\x0cGetMinDisRsp\x12\x0f\n\x07min_dis\x18\x01 \x03(\x02\"\x16\n\x07NumList\x12\x0b\n\x03num\x18\x01 \x03(\x02\":\n\x12\x43ountAndSumListReq\x12$\n\x08num_list\x18\x01 \x03(\x0b\x32\x12.grpc_test.NumList\"\xa1\x01\n\x16\x43ountAndSumResInstruct\x12\x44\n\ncount_dict\x18\x01 \x03(\x0b\x32\x30.grpc_test.CountAndSumResInstruct.CountDictEntry\x12\x0f\n\x07sum_res\x18\x02 \x01(\x02\x1a\x30\n\x0e\x43ountDictEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\"R\n\x12\x43ountAndSumListRsp\x12<\n\x11\x63ount_and_sum_res\x18\x01 \x03(\x0b\x32!.grpc_test.CountAndSumResInstruct\"\x13\n\x06Letter\x12\t\n\x01s\x18\x01 \x01(\t\"9\n\x0fUpperLettersReq\x12&\n\x0bletter_list\x18\x01 \x03(\x0b\x32\x11.grpc_test.Letter\"=\n\x0fUpperLettersRsp\x12*\n\x0fletter_res_list\x18\x01 \x03(\x0b\x32\x11.grpc_test.Letter\"5\n\x0bMessageData\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\x32J\n\tProtoTest\x12=\n\tdoRequest\x12\x16.grpc_test.MessageData\x1a\x16.grpc_test.MessageData\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_test_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_COUNTANDSUMRESINSTRUCT_COUNTDICTENTRY']._options = None
  _globals['_COUNTANDSUMRESINSTRUCT_COUNTDICTENTRY']._serialized_options = b'8\001'
  _globals['_VECTOR']._serialized_start=30
  _globals['_VECTOR']._serialized_end=71
  _globals['_VECTORLIST']._serialized_start=73
  _globals['_VECTORLIST']._serialized_end=124
  _globals['_GETMINDISREQ']._serialized_start=126
  _globals['_GETMINDISREQ']._serialized_end=184
  _globals['_GETMINDISRSP']._serialized_start=186
  _globals['_GETMINDISRSP']._serialized_end=217
  _globals['_NUMLIST']._serialized_start=219
  _globals['_NUMLIST']._serialized_end=241
  _globals['_COUNTANDSUMLISTREQ']._serialized_start=243
  _globals['_COUNTANDSUMLISTREQ']._serialized_end=301
  _globals['_COUNTANDSUMRESINSTRUCT']._serialized_start=304
  _globals['_COUNTANDSUMRESINSTRUCT']._serialized_end=465
  _globals['_COUNTANDSUMRESINSTRUCT_COUNTDICTENTRY']._serialized_start=417
  _globals['_COUNTANDSUMRESINSTRUCT_COUNTDICTENTRY']._serialized_end=465
  _globals['_COUNTANDSUMLISTRSP']._serialized_start=467
  _globals['_COUNTANDSUMLISTRSP']._serialized_end=549
  _globals['_LETTER']._serialized_start=551
  _globals['_LETTER']._serialized_end=570
  _globals['_UPPERLETTERSREQ']._serialized_start=572
  _globals['_UPPERLETTERSREQ']._serialized_end=629
  _globals['_UPPERLETTERSRSP']._serialized_start=631
  _globals['_UPPERLETTERSRSP']._serialized_end=692
  _globals['_MESSAGEDATA']._serialized_start=694
  _globals['_MESSAGEDATA']._serialized_end=747
  _globals['_PROTOTEST']._serialized_start=749
  _globals['_PROTOTEST']._serialized_end=823
# @@protoc_insertion_point(module_scope)
