// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: grpc_test.proto
#ifndef GRPC_grpc_5ftest_2eproto__INCLUDED
#define GRPC_grpc_5ftest_2eproto__INCLUDED

#include "grpc_test.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc_test {

// 定义服务
class GetMimDisService final {
 public:
  static constexpr char const* service_full_name() {
    return "grpc_test.GetMimDisService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status GetMinDis(::grpc::ClientContext* context, const ::grpc_test::GetMinDisReq& request, ::grpc_test::GetMinDisRsp* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::grpc_test::GetMinDisRsp>> AsyncGetMinDis(::grpc::ClientContext* context, const ::grpc_test::GetMinDisReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::grpc_test::GetMinDisRsp>>(AsyncGetMinDisRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::grpc_test::GetMinDisRsp>> PrepareAsyncGetMinDis(::grpc::ClientContext* context, const ::grpc_test::GetMinDisReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::grpc_test::GetMinDisRsp>>(PrepareAsyncGetMinDisRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void GetMinDis(::grpc::ClientContext* context, const ::grpc_test::GetMinDisReq* request, ::grpc_test::GetMinDisRsp* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void GetMinDis(::grpc::ClientContext* context, const ::grpc_test::GetMinDisReq* request, ::grpc_test::GetMinDisRsp* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void GetMinDis(::grpc::ClientContext* context, const ::grpc_test::GetMinDisReq* request, ::grpc_test::GetMinDisRsp* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::grpc_test::GetMinDisRsp>* AsyncGetMinDisRaw(::grpc::ClientContext* context, const ::grpc_test::GetMinDisReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::grpc_test::GetMinDisRsp>* PrepareAsyncGetMinDisRaw(::grpc::ClientContext* context, const ::grpc_test::GetMinDisReq& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status GetMinDis(::grpc::ClientContext* context, const ::grpc_test::GetMinDisReq& request, ::grpc_test::GetMinDisRsp* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::grpc_test::GetMinDisRsp>> AsyncGetMinDis(::grpc::ClientContext* context, const ::grpc_test::GetMinDisReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::grpc_test::GetMinDisRsp>>(AsyncGetMinDisRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::grpc_test::GetMinDisRsp>> PrepareAsyncGetMinDis(::grpc::ClientContext* context, const ::grpc_test::GetMinDisReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::grpc_test::GetMinDisRsp>>(PrepareAsyncGetMinDisRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void GetMinDis(::grpc::ClientContext* context, const ::grpc_test::GetMinDisReq* request, ::grpc_test::GetMinDisRsp* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void GetMinDis(::grpc::ClientContext* context, const ::grpc_test::GetMinDisReq* request, ::grpc_test::GetMinDisRsp* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void GetMinDis(::grpc::ClientContext* context, const ::grpc_test::GetMinDisReq* request, ::grpc_test::GetMinDisRsp* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::grpc_test::GetMinDisRsp>* AsyncGetMinDisRaw(::grpc::ClientContext* context, const ::grpc_test::GetMinDisReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::grpc_test::GetMinDisRsp>* PrepareAsyncGetMinDisRaw(::grpc::ClientContext* context, const ::grpc_test::GetMinDisReq& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetMinDis_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status GetMinDis(::grpc::ServerContext* context, const ::grpc_test::GetMinDisReq* request, ::grpc_test::GetMinDisRsp* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetMinDis : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetMinDis() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetMinDis() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetMinDis(::grpc::ServerContext* /*context*/, const ::grpc_test::GetMinDisReq* /*request*/, ::grpc_test::GetMinDisRsp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetMinDis(::grpc::ServerContext* context, ::grpc_test::GetMinDisReq* request, ::grpc::ServerAsyncResponseWriter< ::grpc_test::GetMinDisRsp>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetMinDis<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_GetMinDis : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_GetMinDis() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc_test::GetMinDisReq, ::grpc_test::GetMinDisRsp>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc_test::GetMinDisReq* request, ::grpc_test::GetMinDisRsp* response) { return this->GetMinDis(context, request, response); }));}
    void SetMessageAllocatorFor_GetMinDis(
        ::grpc::experimental::MessageAllocator< ::grpc_test::GetMinDisReq, ::grpc_test::GetMinDisRsp>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc::internal::CallbackUnaryHandler< ::grpc_test::GetMinDisReq, ::grpc_test::GetMinDisRsp>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_GetMinDis() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetMinDis(::grpc::ServerContext* /*context*/, const ::grpc_test::GetMinDisReq* /*request*/, ::grpc_test::GetMinDisRsp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* GetMinDis(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc_test::GetMinDisReq* /*request*/, ::grpc_test::GetMinDisRsp* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* GetMinDis(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc_test::GetMinDisReq* /*request*/, ::grpc_test::GetMinDisRsp* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_GetMinDis<Service > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_GetMinDis<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetMinDis : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetMinDis() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetMinDis() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetMinDis(::grpc::ServerContext* /*context*/, const ::grpc_test::GetMinDisReq* /*request*/, ::grpc_test::GetMinDisRsp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetMinDis : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetMinDis() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetMinDis() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetMinDis(::grpc::ServerContext* /*context*/, const ::grpc_test::GetMinDisReq* /*request*/, ::grpc_test::GetMinDisRsp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetMinDis(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_GetMinDis : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_GetMinDis() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetMinDis(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_GetMinDis() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetMinDis(::grpc::ServerContext* /*context*/, const ::grpc_test::GetMinDisReq* /*request*/, ::grpc_test::GetMinDisRsp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* GetMinDis(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* GetMinDis(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetMinDis : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetMinDis() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::grpc_test::GetMinDisReq, ::grpc_test::GetMinDisRsp>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::grpc_test::GetMinDisReq, ::grpc_test::GetMinDisRsp>* streamer) {
                       return this->StreamedGetMinDis(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetMinDis() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetMinDis(::grpc::ServerContext* /*context*/, const ::grpc_test::GetMinDisReq* /*request*/, ::grpc_test::GetMinDisRsp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetMinDis(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::grpc_test::GetMinDisReq,::grpc_test::GetMinDisRsp>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetMinDis<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetMinDis<Service > StreamedService;
};

}  // namespace grpc_test


#endif  // GRPC_grpc_5ftest_2eproto__INCLUDED
